# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Contracts Quality Test

on:
  push:
    branches: [develop, audit_1]
  pull_request:
    branches: [develop, main, audit_1]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: cp .env.example .env
      - name: Compile contracts
        run: |
          npx hardhat compile
      - name: Unit tests
        run: |
          npx hardhat test
      - name: Solidity Lint
        run: |
          npx hardhat check
      - name: JS Lint
        run: |
          npx eslint .
      - name: Solidity Test Coverage
        run: npm run coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Solidity contract sizes
        run: npx hardhat size-contracts
